bmw_assembly:
  # Publish all joint states -----------------------------------
  #joint_state_controller:
  #  type: joint_state_controller/JointStateController
  #  publish_rate: 50  

  # velocity Controllers ---------------------------------------
  base_to_belt_velocity_controller:
    type: velocity_controllers/JointVelocityController
    joint: base_to_belt
   # pid: {p: 100.0, i: 0.01, d: 10.0}
  
